name: Scripted maintenance

on: push

jobs:
  maintenance:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Run clang-format
      run: find -type f \( -name *.h -o -name *.cpp \) | xargs clang-format-16 -style=file -i

    - name: Glob files
      run: python ${{ github.workspace }}/ProjectGen.py

    - uses: stefanzweifel/git-auto-commit-action@v5
      with:
        commit_message: maintenance
